project:
  type: book

book:
  title: "Clinical Epidemiology and Seroepidemiology of Non-Typhoidal Salmonella to inform vaccine implementation"
  author: "Helen Dale"
  date: "8/2/2024"
  chapters:
    - index.qmd
    - 1_introduction.qmd
    - 2_methods.qmd
    - 5_Descriptive.qmd
    - summary.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

