project:
  type: book

book:
  author: "Helen Dale"
  title: "Clincal and Seroepidemiology of non-typhoidal salmonenella to inform public health control of invasive disease and vaccine implementation"
  date: today
  date-format: "MMMM YYYY"
  chapters:
    - index.qmd
    - 1-introduction.qmd
    - 2-methods.qmd
    - 5_Descriptive.qmd
    - summary.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt
    papersize: a4
    header-includes: |
      \usepackage{titling}
      \pretitle{\begin{center}
        \includegraphics[width=5in,height=4in]{figures/UoL_logo.png}\\ % cover figure
        \Large
        \vspace{8mm}
      }
      \posttitle{
        \vspace{20mm}
        \end{center}
      }
      \setlength{\droptitle}{-2cm}
      \preauthor{
        \begin{center}
        Thesis submitted in accordance with the requirements of the University of Liverpool for the degree of Doctor of Philosophy\\
        \vspace{20mm}
        }
        \postauthor{
         \end{center}
        }
        \predate{
         \begin{center}
          MBChB, DTM\&H, MSc, MRes\\
          \vspace{8mm}
        }
        \postdate{
          \end{center}
          \newpage
          \mbox{}
          \vfill
         }

editor: visual

